=== ElectroBlocks/ElectroBlocks-Legacy/src/app/components/lesson/lesson.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/LessonModel",
  "definitions": {
    "LessonModel": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "objective": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "billOfMaterial": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "cost": {
                "type": "string"
              },
              "quantity": {
                "type": "number"
              }
            },
            "required": ["name", "cost", "quantity"],
            "additionalProperties": false
          }
        },
        "slides": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SlideModel"
          }
        },
        "googleFormUrl": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "author",
        "objective",
        "image",
        "billOfMaterial",
        "slides",
        "googleFormUrl"
      ],
      "additionalProperties": false
    },
    "SlideModel": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "src": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "STEP",
            "VIDEO",
            "IMAGE",
            "VIDEO_CHALLENGE_QUESTION",
            "VIDEO_CHALLENGE_ANSWER"
          ]
        },
        "step": {
          "type": "number"
        }
      },
      "required": ["title", "src", "text", "type"],
      "additionalProperties": false
    }
  }
}

=== ElectroBlocks/ElectroBlocks-Legacy/src/app/components/lesson/lessons/lesson-1.json
{
  "$schema": "../lesson.schema.json",
  "author": "Noah Glaser",
  "title": "Arduino Introduction",
  "billOfMaterial": [
    {
      "cost": "7.00",
      "name": "Arduino with cables",
      "quantity": 1
    }
  ],
  "googleFormUrl": "blah",
  "image": "https://github.com/phptuts/codingwithnoah/blob/master/images/arduino-block/arduino-intro/project.jpg",
  "objective": "To learn how the Arduino Works!",
  "slides": [
    {
      "step": 0,
      "title": "What is an Arduino?",
      "src": "http://www.codingwithnoah.com/images/arduino-block/arduino-intro/arduino.jpg",
      "type": "IMAGE",
      "text": "The Arduino is a cheap real time computer that costs around 7 dollars. Real time means that will execute your code really fast. It can do this because there is no operating system running on the Arduino. The only thing itâ€™s doing is running your code. :)"
    }
  ]
}
